targets:
  BookStoreFoundation:
    templates: [StaticFramework]

  BookStoreFoundationTests:
    templates: [UnitTest]
    templateAttributes:
      testTarget: BookStoreFoundation

schemes:
  AllTests:
    build:
      targets:
        BookStoreFoundation: test
    test:
      targets:
        - BookStoreFoundationTests
